### ISSUE TITLE
[提案]Readmeの手順の行間を補完する

### ISSUE THREAD

**Issue by wing3298** [co-meeting/how-are-you-today-bot#3]
Firebaseのセットアップ部分で初見では難易度高そうな部分を補完したらわりとすんなり行けそうです

> 事前準備
> 
> (アカウントがなければ)Firebaseのアカウントを作成する
> Firebaseのプロジェクトを作成する
> Firebaseの外部公開URLを Request URLへ設定
> firebaseコマンドをローカルにインストールする

・Firebaseのアカウント作成のためのWebリンクがあるといいかも
・Fireabseのプロジェクト作成は
`firebase init`
の実行なのかな・・？
・コマンドのインストールが先で、公開URLの設定はデプロイ後かな・・？

`firebase functions:config:set slack.secret=[Signing Secret]`
がないと認証エラーになってしまうので必ず必要かな・・？

**Comment by atskimura** [comment]
ありがとうございます。Firebase周りは不親切でしたね。確認して追記します。

**Comment by atskimura** [comment]
@wing3298 README書き直しました。
`slack.secret` は必要ないはずですね。
SlackアプリとFirebaseプロジェクトを作り直して試したので問題ないと思います。
